### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by igneus** [noteflakes/lyp-lilyjazz#1]
```
me@home:~$ lyp install lilyjazz
Installing package fonts...
No such file or directory @ rb_sysopen - /usr/share/lilypond/current/fonts/otf/LilyJAZZText.otf
me@home:~$ lyp -v
Lyp 0.3.3
```

**Comment by igneus** [comment]
Testing has proved that it's not an issue of the package, but a limitation of lyp: packages containing fonts don't work with system lilyponds (i.e. those not installed by lyp). As this most probably cannot be fixed, the issue can be closed. The limitation is possibly worth mentioning somewhere.

**Comment by noteflakes** [comment]
Yeah that should be a bug in lyp itself. I'll give it a look tomorrow.

**Comment by ciconia** [comment]
@igneus So I could pin-point the problem, could you tell me how lilypond is installed on your system - where exactly is lilypond's share directory? Do you have multiple versions of lilypond? Are there any directories under `/usr/share/lilypond`? Is there anything under `/usr/local/share/lilypond`?

**Comment by noteflakes** [comment]
@igneus I pushed a new version (0.3.4) that should fix this. Please test and let me know if the problem is solved.

**Comment by igneus** [comment]
Unfortunately not.

So here is the information you requested earlier today:

# lilyponds

```
$ lyp list lilypond

Lilypond versions:

   2.14.2 (system)
   2.18.2 (system)
 * 2.19.32 (system)
=> 2.19.36

# => - current
# =* - current && default
#  * - default
```

2.14.2 lives in `~/apps/bin/lilypond` and `~/apps/share/lilypond/`
2.18.2 in `/usr/bin/lilypond` and `/usr/share/lilypond`
2.19.32 in `~/apps/lilypond-git/build/out/bin/lilypond` and `~/apps/lilypond-git/build/out/share`
2.19.36 is installed using lyp

# requested directories and their content

`/usr/local/share/lilypond` doesn't even exist and `/usr/share/lilypond` contains a single directory named `2.18.2`

**Comment by igneus** [comment]
Oh and I should have mentioned: output changed from yesterday. Today it says

```
$ lyp install lilyjazz
Installing package fonts...
patch /usr/share/lilypond/2.18.2/scm/font.scm
Permission denied @ rb_sysopen - /usr/share/lilypond/2.18.2/scm/font.scm

$ lyp -v # show I have the latest gem version
Lyp 0.3.4
```

**Comment by igneus** [comment]
I should add that deleting, writing or patching files in lilypond installations not produced by lyp (the output suggests that exactly this is being attempted) aren't a good practice. I would expect that the application either asks if it is allowed to or doesn't attempt it at all.

I usually have a few local lilypond installations in my home directory, that are writable. But I would kindly ask `lyp` not to touch them, even if it should mean that some packages won't work well with these installations.

**Comment by noteflakes** [comment]
You're right. Back to the code...

**Comment by noteflakes** [comment]
Please test again with the lyp version I just released. It asks for confirmation both before patching and copying font files to system-installed lilyponds. It also tries to sudo copy the files (asking for password) if the files are not writable by the current user.

**Comment by igneus** [comment]
It works great. Thank you very much.
